Feat/restaurant detail api
posomo/saltit-server pull request #32
Opened 2023-04-24 15:13 UTC by inhyeokjo

## 🤩 개요
식당 상세 페이지 API 구현
- 사이드 메뉴와 주 메뉴를 구분해서 보여줘야 한다.
- 가격과 이름, 전체 메뉴 갯수, 주/사이드 메뉴 갯수를 보여준다.

## 🧑‍💻 작업 사항
- Controller/Service/Repositroy 구현
- Test Code 구현
- Controller Advice 구현

## 📖 참고 사항
- 기존 코드 리팩토링 필요

2023-04-24 15:15 UTC, jhbaik1501 commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.26'
버젼을 명시하신 이유가 따로 있으실까요?

2023-04-24 15:32 UTC, jhbaik1501 commented on src/main/java/com/posomo/saltit/global/aop/ControllerAdvice.java
> +		return "해당 레코드는 존재하지 않습니다.";
ResponseCode와 같이 ENUM 상수로 관리하는게 좋지 않을까요?

2023-04-24 15:55 UTC, jhbaik1501 commented on src/main/java/com/posomo/saltit/controller/RestaurantController.java
> +    public RestaurantDetailResponse getRestaurantDetail(@PathVariable("restaurantId") @NotBlank Integer restaurantId) {
ControllerAdvice에서 @NotBlank 오류를 잡아야할것 같네요

2023-04-24 15:56 UTC, jhbaik1501 commented on src/main/java/com/posomo/saltit/controller/RestaurantController.java
> +    public RestaurantDetailResponse getRestaurantDetail(@PathVariable("restaurantId") @NotBlank Integer restaurantId) {
어차피 Integer로 받으면 @NotBlank를 붙이지 않아도 되지 않을까요?

2023-04-24 16:01 UTC, jhbaik1501 commented on src/test/java/com/posomo/saltit/respository/RestaurantRepositoryTest.java
> +		@DisplayName("정상흐름")
뭐가 정상흐름인지 잘 모르겠어요

2023-04-24 16:07 UTC, inhyeokjo commented on src/test/java/com/posomo/saltit/respository/RestaurantRepositoryTest.java
> +		@DisplayName("정상흐름")
@Nested 뒤에 @DisplayName()을 추가해서 어떤 메소드를 테스트하는지 설명하겠습니다!

2023-04-24 16:13 UTC, jhbaik1501 commented on src/test/java/com/posomo/saltit/service/RestaurantServiceTest.java
> +			Mockito.when(restaurantRepository.findByIdWithMenus(1L)).thenReturn(Optional.of(restaurant));
Mockito를 import static org.mockito.Mockito.*; 빼는 건 어때보이나요?

2023-04-24 16:13 UTC, inhyeokjo commented on src/test/java/com/posomo/saltit/service/RestaurantServiceTest.java
> +			Mockito.when(restaurantRepository.findByIdWithMenus(1L)).thenReturn(Optional.of(restaurant));
그게 맞습니다. 실수입니다. 죄송합니다.

2023-04-24 16:21 UTC, inhyeokjo commented on src/main/java/com/posomo/saltit/controller/RestaurantController.java
> +    public RestaurantDetailResponse getRestaurantDetail(@PathVariable("restaurantId") @NotBlank Integer restaurantId) {
반영했습니다!

2023-04-24 16:22 UTC, inhyeokjo commented on src/test/java/com/posomo/saltit/service/RestaurantServiceTest.java
> +			Mockito.when(restaurantRepository.findByIdWithMenus(1L)).thenReturn(Optional.of(restaurant));
반영했습니다!

2023-04-25 10:03 UTC, inhyeokjo commented on src/test/java/com/posomo/saltit/respository/RestaurantRepositoryTest.java
> +		@DisplayName("정상흐름")
반영했습니다!

2023-04-25 10:09 UTC, inhyeokjo commented on build.gradle
> +    implementation 'org.projectlombok:lombok:1.18.26'
버전을 명시하지 않으면 의존성을 찾지 못하는 버그가 있어서 명시했습니다.
<img width="683" alt="image" src="https://user-images.githubusercontent.com/68802559/234245408-ffaed794-515d-41c6-8cc7-1a64e143eb62.png">

2023-04-26 10:02 UTC, johan1103 requested changes

2023-04-26 10:02 UTC, johan1103 commented on src/main/java/com/posomo/saltit/domain/restaurant/dto/RestaurantDetailResponse.java
> +	private Classification side;
DTO에서 사이드 메뉴와 메인 메뉴를 따로 제공하는 이유는 저희 서비스 식당 상세페이지에서 메인 메뉴량 사이드 메뉴를 다른 섹션에서 보여주기 때문일까요?

2023-04-26 10:02 UTC, johan1103 commented on src/main/java/com/posomo/saltit/domain/restaurant/dto/RestaurantDetailResponse.java
### 리뷰 확인 기능
<img width="161" alt="image" src="https://user-images.githubusercontent.com/71641610/234539652-a3fdb575-e410-4b1f-a6f0-96770a3b1b67.png">
요 컴포넌트를 클릭하면 웹 뷰 형식으로 다이닝코드의 리뷰 페이지 보여줘야 합니다!

다이닝 코드는 [https://m.diningcode.com/review/list.php?rid="식당 고유 rid"] 형식으로 리뷰 정보를 제공하고 있습니다.
**고래서 저희 DB에 저장되어 있는 다이닝코드의 rid값을 DTO에 담아줘야 할 것 같습니다!**

리뷰 화면 링크 예시
[https://m.diningcode.com/review/list.php?rid=LMy6BQjFbE2W](url)

 🤔  그리고 다이닝코드의 [Robots.txt](https://www.diningcode.com/robots.txt)에서 리뷰 정보는 크롤링을 권고하지 않기 때문에  따로 크롤링 하지 않았습니다!

2023-04-26 10:06 UTC, inhyeokjo commented on src/main/java/com/posomo/saltit/domain/restaurant/dto/RestaurantDetailResponse.java
> +	private Classification side;
넵 맞습니다

2023-04-26 10:07 UTC, inhyeokjo commented on src/main/java/com/posomo/saltit/domain/restaurant/dto/RestaurantDetailResponse.java
주소를 통째로 보내주는 편이 더 좋지 않을까요? 주소가 변경되었을 때 서버는 저희가 일괄 적으로 변경할 수 있지만, 안드로이드는 어플이라서 사용자가 업데이트 하지 않으면 수정되지 않으니까요!

2023-04-26 10:16 UTC, inhyeokjo commented on src/main/java/com/posomo/saltit/global/aop/ControllerAdvice.java
> +		return "해당 레코드는 존재하지 않습니다.";
반영했습니다. ENUM을 사용하지는 않았고 그냥 상수로 빼서 관리하도록 변경했습니다. 추후에 리뷰 바랍니다!

2023-04-26 10:39 UTC, inhyeokjo commented on src/main/java/com/posomo/saltit/domain/restaurant/dto/RestaurantDetailResponse.java
반영했습니다.

2023-04-26 10:45 UTC, jhbaik1501 approved these changes
Good

2023-04-26 10:45 UTC, johan1103 approved these changes

2023-04-26 10:55 UTC, merged